### ISSUE TITLE
Do you considering to release the pre-trained model?

### ISSUE THREAD

**Issue by BboyHanat** [ac-rad/MVTrans#3]
This is a excellent work, but I do not find the model in this project, do you considering to release the model? that will  convenient to validate the result~

**Comment by BboyHanat** [comment]
And I find dataset link in your project page is "https://ac-rad.github.io/MVTrans/", but no dataset link. can you fix it?

**Comment by Jack-XHP** [comment]
Hi we just upload our pretrained weights, you can find download link in our repo readme
